.org 0x08D34940
.include Graphics/TitleScreen/TitleScreen_relocate.asm
.include Graphics/Rhythm_Games/Karate_Man/KarateMan1_relocate.asm
.include Graphics/MainMenu/mainmenu_relocate.asm
.include Graphics/Tutorial/tutorial_relocate.asm
.include Graphics/EmailSelectScreen/email_relocate.asm
.include Graphics/MusicSelect/musictest_relocate.asm
.include Graphics/ToysMenu/toymenu_relocate.asm
.include Graphics/Drums/drums_relocate.asm
.include Graphics/Options/options_relocate.asm
.include Graphics/EndlessMenu/endless_relocate.asm
.include Graphics/RhythemGameSelect/gameselect_relocate.asm
.include Graphics/RhythmGame/Results/Results_relocate.asm
.include Graphics/RhythmGame/spaceball1/spaceball1_relocate.asm
.include Graphics/RhythmGame/Veggie1/Veggie1_relocate.asm
.include Graphics/Rhythm_Games/Marching_Orders/Marcher1_relocate.asm
.include Graphics/Rhythm_Games/The_Clappy_Trio/clappy1_relocate.asm
.include Graphics/RhythmGame/remix1/mix1_relocate.asm
.include Graphics/RhythmGame/miscgraphics_relocate.asm
.include Graphics/RhythmGame/spirit1/spirit1_relocate.asm
.include Graphics/RhythmGame/Samurai/samurai_relocate.asm
.include Graphics/Rhythm_Games/Cheese_Heist/cheese_relocate.asm
.include Graphics/RhythmGame/SickBeats/SickBeats_relocate.asm
.include Graphics/Rhythm_Games/TheBon_Odori/odori1_relocate.asm
.include Graphics/RhythmGame/remix2/mix2_relocate.asm
.include Graphics/RhythmGame/wizard/wizard_relocate.asm
.include Graphics/RhythmGame/Showtime/showtime_relocate.asm
.include Graphics/Rhythm_Games/Bunny_Hop/bunny_relocate.asm
.include Graphics/RhythmGame/Tram/tram_relocate.asm
.include Graphics/Rhythm_Games/Space_Dance/space1_relocate.asm
.include Graphics/RhythmGame/Remix3/remix3_relocate.asm
.include Graphics/RhythmGame/Quiz/quiz_relocate.asm
.include Graphics/Rhythm_Games/Night_Walk/night1_relocate.asm
.include Graphics/Rhythm_Games/Power_Calligraphy/calig_relocate.asm
.include Graphics/Rhythm_Games/Built_To_Scale/built1_relocate.asm
.include Graphics/RhythmGame/Rapmen/rapmen_relocate.asm
.include Graphics/RhythmGame/Remix4/remix4_relocate.asm
.include Graphics/Rhythm_Games/Bouncy_Road/hop1_relocate.asm
.include Graphics/Rhythm_Games/Ninja_Bodyguard/ninja1_relocate.asm
.include Graphics/RhythmGame/Toss1/toss1_relocate.asm
.include Graphics/Rhythm_Games/Fireworks/fworks_relocate.asm
.include Graphics/RhythmGame/Tap1/tap1_relocate.asm
.include Graphics/RhythmGame/Remix5/remix5_relocate.asm
.include Graphics/Rhythm_Games/The_Snappy_Trio/clappy2_relocate.asm
.include Graphics/RhythmGame/Odori2/bon2_relocate.asm
.include Graphics/Rhythm_Games/Cosmic_Dance/cosmo2_relocate.asm
.include Graphics/RhythmGame/RapWomen2/rapwom_relocate.asm
.include Graphics/RhythmGame/Tap2/tap2_relocate.asm
.include Graphics/RhythmGame/Remix6/remix6_relocate.asm
.include Graphics/RhythmGame/Ninja2/ninja2_relocate.asm
.include Graphics/Rhythm_Games/Marching_Orders_2/march2_relocate.asm
.include Graphics/RhythmGame/Remix7/remix7_relocate.asm
.include Graphics/RhythmGame/Toss2/toss2_relocate.asm
.include Graphics/RhythmGame/Remix8/remix8_relocate.asm
.include Graphics/ToysMenu/Toys/toys_relocate.asm
.include Graphics/EndlessMenu/games/games_relocate.asm
.include Graphics/WarningScreen/warningscreen_relocate.asm
;eof