.org 0x08D34940
.include Graphics/TitleScreen/TitleScreen_relocate.asm
.include Graphics/RhythmGame/KarateMan1/KarateMan1_relocate.asm
.include Graphics/MainMenu/mainmenu_relocate.asm
.include Graphics/Tutorial/tutorial_relocate.asm
.include Graphics/EmailSelectScreen/email_relocate.asm
.include Graphics/MusicSelect/musictest_relocate.asm
.include Graphics/ToysMenu/toymenu_relocate.asm
.include Graphics/Drums/drums_relocate.asm
.include Graphics/Options/options_relocate.asm
.include Graphics/EndlessMenu/endless_relocate.asm
.include Graphics/RhythemGameSelect/gameselect_relocate.asm
.include Graphics/RhythmGame/Results/Results_relocate.asm
.include Graphics/RhythmGame/spaceball1/spaceball1_relocate.asm
.include Graphics/RhythmGame/Veggie1/Veggie1_relocate.asm
.include Graphics/RhythmGame/marcher1/Marcher1_relocate.asm
.include Graphics/RhythmGame/clappy1/clappy1_relocate.asm
.include Graphics/RhythmGame/remix1/mix1_relocate.asm
.include Graphics/RhythmGame/miscgraphics_relocate.asm
.include Graphics/RhythmGame/spirit1/spirit1_relocate.asm
.include Graphics/RhythmGame/Samurai/samurai_relocate.asm
.include Graphics/RhythmGame/Cheese/cheese_relocate.asm
.include Graphics/RhythmGame/DrBact/drbact_relocate.asm
.include Graphics/RhythmGame/bonodori1/odori1_relocate.asm
.include Graphics/RhythmGame/remix2/mix2_relocate.asm
.include Graphics/RhythmGame/wizard/wizard_relocate.asm
.include Graphics/RhythmGame/Showtime/showtime_relocate.asm
.include Graphics/RhythmGame/BunnyHop/bunny_relocate.asm
.include Graphics/RhythmGame/Tram/tram_relocate.asm
.include Graphics/RhythmGame/Space1/space1_relocate.asm
.include Graphics/RhythmGame/Remix3/remix3_relocate.asm
.include Graphics/RhythmGame/Quiz/quiz_relocate.asm
.include Graphics/RhythmGame/Nightwalk/night1_relocate.asm
.include Graphics/RhythmGame/Calig/calig_relocate.asm
.include Graphics/RhythmGame/built1/built1_relocate.asm
.include Graphics/RhythmGame/Rapmen/rapmen_relocate.asm
.include Graphics/RhythmGame/Remix4/remix4_relocate.asm
.include Graphics/RhythmGame/Hop1/hop1_relocate.asm
.include Graphics/RhythmGame/Ninja1/ninja1_relocate.asm
.include Graphics/RhythmGame/Toss1/toss1_relocate.asm
.include Graphics/RhythmGame/Fworks/fworks_relocate.asm
.include Graphics/RhythmGame/Tap1/tap1_relocate.asm
.include Graphics/RhythmGame/Remix5/remix5_relocate.asm
.include Graphics/RhythmGame/clappy2/clappy2_relocate.asm
.include Graphics/RhythmGame/Odori2/bon2_relocate.asm
.include Graphics/RhythmGame/cosmo2/cosmo2_relocate.asm
.include Graphics/RhythmGame/RapWomen2/rapwom_relocate.asm
.include Graphics/RhythmGame/Tap2/tap2_relocate.asm
.include Graphics/RhythmGame/Remix6/remix6_relocate.asm
.include Graphics/RhythmGame/Ninja2/ninja2_relocate.asm
.include Graphics/RhythmGame/Marcher2/march2_relocate.asm
.include Graphics/RhythmGame/Remix7/remix7_relocate.asm
.include Graphics/RhythmGame/Toss2/toss2_relocate.asm
.include Graphics/RhythmGame/Remix8/remix8_relocate.asm
.include Graphics/ToysMenu/Toys/toys_relocate.asm
.include Graphics/WarningScreen/warningscreen_relocate.asm
;eof