.org 0x08D34940
.include EN_SourceCode/Graphics/TitleScreen/TitleScreen_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Karate_Man/KarateMan1_relocate.asm
.include EN_SourceCode/Graphics/MainMenu/mainmenu_relocate.asm
.include EN_SourceCode/Graphics/Tutorial/tutorial_relocate.asm
.include EN_SourceCode/Graphics/EmailSelectScreen/email_relocate.asm
.include EN_SourceCode/Graphics/MusicSelect/musictest_relocate.asm
.include EN_SourceCode/Graphics/ToysMenu/toymenu_relocate.asm
.include EN_SourceCode/Graphics/Drums/drums_relocate.asm
.include EN_SourceCode/Graphics/Options/options_relocate.asm
.include EN_SourceCode/Graphics/EndlessMenu/endless_relocate.asm
.include EN_SourceCode/Graphics/RhythemGameSelect/gameselect_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Results_Screen/Results_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Spaceball/spaceball1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Rhythm_Tweezers/Veggie1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Marching_Orders/Marcher1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/The_Clappy_Trio/clappy1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Remix_1/mix1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/MiscGraphics/miscgraphics_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Sneaky_Spirits/spirit1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Samurai_Slice/samurai_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Cheese_Heist/cheese_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Sick_Beats/SickBeats_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/TheBon_Odori/odori1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Remix_2/mix2_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Death_Waltz/wizard_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Showtime/showtime_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Bunny_Hop/bunny_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Tram_Pauline/tram_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Space_Dance/space1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Remix_3/remix3_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Quiz_Show/quiz_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Night_Walk/night1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Power_Calligraphy/calig_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Polyrhythm/built1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Rap_Men/rapmen_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Remix_4/remix4_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Bouncy_Road/hop1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Ninja_Bodyguard/ninja1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Toss_Boys/toss1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Fireworks/fworks_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Tap_Trial/tap1_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Remix_5/remix5_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/The_Snappy_Trio/clappy2_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/TheBon_Dance/bon2_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Cosmic_Dance/cosmo2_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Rap_Women/rapwom_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Turbo_Tap_Trial/tap2_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Remix_6/remix6_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Ninja_Bodyguard_2/ninja2_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Marching_Orders_2/march2_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Remix_7/remix7_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Toss_Boys_2/toss2_relocate.asm
.include EN_SourceCode/Graphics/Rhythm_Games/Remix_8/remix8_relocate.asm
.include EN_SourceCode/Graphics/ToysMenu/Toys/toys_relocate.asm
.include EN_SourceCode/Graphics/EndlessMenu/games/games_relocate.asm
.include EN_SourceCode/Graphics/Warning_Screen/warningscreen_relocate.asm
;eof