.align 4
D1AD4C_warningscreen_tile:
.import Graphics/WarningScreen/D1AD4C_warningscreen_tile.cdat
.align 4
D1AD4C_warningscreen_tile_map_dat:
.import Graphics/WarningScreen/D1AD4C_warningscreen_tile_map.dat
.align 4
D1AD4C_warningscreen_tile_map_rle:
.import Graphics/WarningScreen/D1AD4C_warningscreen_tile_map.rle
D1AD4C_warningscreen_tile_map_rle_end:
;eof