.align 4
D1AD4C_warningscreen_tile:
.import EN_SourceCode/Graphics/Warning_Screen/D1AD4C_warningscreen_tile.cdat
.align 4
D1AD4C_warningscreen_tile_map_dat:
.import EN_SourceCode/Graphics/Warning_Screen/D1AD4C_warningscreen_tile_map.dat
.align 4
D1AD4C_warningscreen_tile_map_rle:
.import EN_SourceCode/Graphics/Warning_Screen/D1AD4C_warningscreen_tile_map.rle
D1AD4C_warningscreen_tile_map_rle_end:
;eof