.align 4
CC9148_rhythemgameselect_oams_tiles:
.import Graphics/RhythemGameSelect/CC9148_rhythemgameselect_oams_tiles.cdat
.align 4
CC9854_rhythemgamesselect_bg1_tiles:
.import Graphics/RhythemGameSelect/CC9854_rhythemgamesselect_bg1_tiles.cdat
;eof